# Numpy

NumPy is a Python library for handling multi-dimensional arrays. It contains both the data structures needed for the storing and accessing arrays, and operations and functions for computation using these arrays. Although the arrays are usually used for storing number, other type of data can be stored as well, such as strings. Unlike lists in core Python, NumPy's fundamental data structure, the array, must have the same data type for all its elements. The homogeneity of arrays allows highly optimized functions that use arrays as their inputs.

There are several uses for high-dimensional arrays in data analysis. For instance, they can be used to:

* store matrices, solve systems of linear equations, find eigenvalues/vectors, find matrix decompositions, and solve other problems familiar from linear algebra
* store multi-dimensional measurement data. For example, an element a_ij in a 2-dimensional array might store the temperature measured at coordinates i, j on a 2-dimension surface.
* images and videos can be represented as NumPy arrays:

  * a gray-scale image can be represented as a two dimensional array
  * a color image can be represented as a three dimensional image, the third dimension contains the color components red, green, and blue
  * a color video can be represented as a four dimensional array
* a 2-dimensional table might store a sequence of *samples*, and each sample might be divided into *features*. For example, we could measure the weather conditions once per day, and the conditions could include the temperature, direction and speed of wind, and the amount of rain. Then we would have one sample per day, and the features would be the temperature, wind, and rain. In the standard representation of this kind of tabular data, we the rows corresponds to samples and the columns correspond to features. We see more of this kind of data in the chapters on Pandas and Scikit-learn.

In this chapter we will go through:

* Creation of arrays
* Array types and attributes
* Accessing arrays with indexing and slicing
* Reshaping of arrays
* Combining and splitting arrays
* Fast operations on arrays
* Aggregations of arrays
* Rules of binary array operations
* Matrix operations familiar from linear algebra

We start by importing the NumPy library, and we use the standard abbreviation `np` for it.

In [1]:
import numpy as np

## Creation of arrays
There are several ways of creating numpy arrays. One way is to give a (nested) list as a parameter to the `array` constructor:

In [2]:
np.array([1,2,3])   # one dimensional array

array([1, 2, 3])

Note that leaving out the brackets from the above expression, i.e. calling `np.array(1,2,3)` will result in an error.

Two dimensional array can be given by listing the rows of the array:

In [3]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

Similarly, three dimensional array can be described as a list of lists of lists:

In [4]:
np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

There are some helper functions to create common types of arrays:

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

To specify that elements are ints instead of float, use the parameter dtype:

In [6]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Similarly `ones` initializes all elements to one, `full` initializes all elements to a specified value, and `empty` leaves the elements uninitialized:

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.full((2,3), fill_value=7)

array([[7, 7, 7],
       [7, 7, 7]])

In [9]:
np.empty((2,4))

array([[6.90170349e-310, 4.66312875e-310, 0.00000000e+000,
        0.00000000e+000],
       [2.37151510e-322, 5.53353523e-322, 0.00000000e+000,
        3.16202013e-322]])

The `eye` function creates the identity matrix, that is, a matrix with elements on the diagonal are set to one, and non-diagonal elements are set to zero:

In [10]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

The `arange` function works like the `range` function, but produces an array instead of a list.

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

For non-integer ranges it is better to use `linspace`:

In [12]:
np.linspace(0, np.pi, 5)  # Evenly spaced range with 5 elements

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

With `linspace` one does not have compute the length of the step, but instead one specifies the wanted number of elements. By default, the endpoint is included in the result, unlike with `arange`.

### Arrays with random elements

To test our programs we might use real data as input. However, real data is not always available, and it may take time to gather. We could instead generate random numbers to use as substitute. They can be generated really easily with NumPy, and can be sampled from several different distribution, of which we mention below only a few. Random data can simulate real data better than, for example, ranges or constant arrays. Sometimes we also need random numbers in our programs to choose a subset of real data. NumPy can easily produces arrays of wanted shape filled with random numbers. Below are few examples.

In [13]:
np.random.random((3,4))          # Elements are uniformly distributed from half-open interval [0.0,1.0)

array([[0.886096  , 0.55756628, 0.6478361 , 0.54100462],
       [0.91835784, 0.76684297, 0.27486936, 0.5155221 ],
       [0.22480377, 0.44763123, 0.43477361, 0.79683321]])

In [14]:
np.random.normal(0, 1, (3,4))    # Elements are normally distributed with mean 0 and standard deviation 1

array([[ 0.9382291 , -0.93755962,  0.90853183, -0.5239464 ],
       [-1.09882169, -0.82543964,  2.26272302,  0.55225504],
       [-0.23552639,  1.47078892, -0.80461278,  0.17321221]])

In [15]:
np.random.randint(-2, 10, (3,4))  # Elements are uniformly distributed integers from the half-open interval [-2,10)

array([[ 8,  2, -1,  1],
       [ 6,  3,  2,  7],
       [ 4,  8,  8, -1]])

Sometimes it is useful to be able to recreate exactly the same data in every run of our program. For example, if there is a bug in our program, which manifests itself only with certain input, then to debug our program it needs to behave deterministically. We can create random numbers deterministically, if we always start from the same starting point. This starting point is usually an integer, and we call it a *seed*. Example of use:

In [16]:
np.random.seed(0)
print(np.random.randint(0, 100, 10))
print(np.random.normal(0, 1, 10))

[44 47 64 67 67  9 83 21 36 87]
[ 1.26611853 -0.50587654  2.54520078  1.08081191  0.48431215  0.57914048
 -0.18158257  1.41020463 -0.37447169  0.27519832]


If you run the above cell multiple times, it will always give the same number, unlike the earlier examples. Try rerunning them now!

The call to `np.random.seed` initializes the *global* random number generator. The calls `np.random.random`, `np.random.normal`, etc all use this global random number generator. It is however possible to generate new random number generators, and use those to sample random numbers from a distribution. Example on usage:

In [17]:
new_generator = np.random.RandomState(seed=123)  # RandomState is a class, so we give the seed to its constructor
new_generator.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

You will see these used later in the materials and in the exercises, just so we can agree what the random input data is. How else could we agree whether result is correct or not, if we can't agree what the input is!

## Array types and attributes

An array has several attributes: ndim tells the number of dimensions, shape tells the size in each dimension, size tells the number of elements, and dtype tells the element type. Let's create a helper function to explore these attributes:

In [18]:
def info(name, a):
    print("%s has dim %i, shape %s, size %i, and dtype %s:" % (name, a.ndim, a.shape, a.size, a.dtype))
    print(a)

In [19]:
b=np.array([[1,2,3], [4,5,6]])
info("b", b)

b has dim 2, shape (2, 3), size 6, and dtype int64:
[[1 2 3]
 [4 5 6]]


In [20]:
c=np.array([b, b])          # Creates a 3-dimensional array
info("c", c)

c has dim 3, shape (2, 2, 3), size 12, and dtype int64:
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [21]:
d=np.array([[1,2,3,4]])                # a row vector
info("d", d)

d has dim 2, shape (1, 4), size 4, and dtype int64:
[[1 2 3 4]]


Note above how Python printed the three dimensional array. The general rules of printing an n-dimensional array as a nested list are:
* the last dimension is printed from left to right,
* the second-to-last is printed from top to bottom,
* the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

## Indexing, slicing and reshaping

### Indexing
One dimensional array behaves like the list in Python:

In [22]:
a=np.array([1,4,2,7,9,5])
print(a[1])
print(a[-2])

4
9


For multi-dimensional array the index is a comma separated tuple instead of a single integer:

In [23]:
b=np.array([[1,2,3], [4,5,6]])
print(b)
print(b[1,2])    # row index 1, column index 2
print(b[0,-1])   # row index 0, column index -1

[[1 2 3]
 [4 5 6]]
6
3


In [24]:
# As with lists modification through indexing is possible
b[0,0] = 10
print(b)

[[10  2  3]
 [ 4  5  6]]


Note that if you give only a single index to a multi-dimensional array, it indexes the first dimension of the array, that is then rows. For example:

In [25]:
print(b[0])    # First row
print(b[1])    # Second row

[10  2  3]
[4 5 6]


#### Slicing
Slicing works similarly to lists, but now we can have slice in different dimensions:

In [26]:
print(a)
print(a[1:3])
print(a[::-1])    # Reverses the array

[1 4 2 7 9 5]
[4 2]
[5 9 7 2 4 1]


In [27]:
print(b)
print(b[:,0])
print(b[0,:])
print(b[:,1:])

[[10  2  3]
 [ 4  5  6]]
[10  4]
[10  2  3]
[[2 3]
 [5 6]]


We can even assign to a slice:

In [28]:
b[:,1:] = 7
print(b)

[[10  7  7]
 [ 4  7  7]]


A common idiom is to extract rows or columns from an array:

In [29]:
print(b[:,0])    # First column
print(b[1,:])    # Second row

[10  4]
[4 7 7]


### Reshaping

When an array is reshaped, its number of elements stays the same, but they are reinterpreted to have a different shape. An example of this is to interpret a one dimensional array as two dimension array:

In [30]:
a=np.arange(9)
anew=a.reshape(3,3)
info("anew", anew)
info("a", a)

anew has dim 2, shape (3, 3), size 9, and dtype int64:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
a has dim 1, shape (9,), size 9, and dtype int64:
[0 1 2 3 4 5 6 7 8]


In [31]:
d=np.arange(4)             # 1d array
dr=d.reshape(1,4)          # row vector
dc=d.reshape(4,1)          # column vector
info("d", d)
info("dr", dr)
info("dc", dc)

d has dim 1, shape (4,), size 4, and dtype int64:
[0 1 2 3]
dr has dim 2, shape (1, 4), size 4, and dtype int64:
[[0 1 2 3]]
dc has dim 2, shape (4, 1), size 4, and dtype int64:
[[0]
 [1]
 [2]
 [3]]


<div class="alert alert-warning">
Note the 1d array and the row and column vectors, which are 2d arrays, are fundamentally different objects, even though they look similar. They behave differently when we combine or otherwise operate arrays of different shapes, as we shall see in the next section and later in this material.
</div>

An alternative syntax to create, for example, column or row vectors is through the `np.newaxis` keyword. Sometimes this is more easier or natural than with the reshape method:

In [32]:
info("d", d)
info("drow", d[:, np.newaxis])
info("drow", d[np.newaxis, :])
info("dcol", d[:, np.newaxis])

d has dim 1, shape (4,), size 4, and dtype int64:
[0 1 2 3]
drow has dim 2, shape (4, 1), size 4, and dtype int64:
[[0]
 [1]
 [2]
 [3]]
drow has dim 2, shape (1, 4), size 4, and dtype int64:
[[0 1 2 3]]
dcol has dim 2, shape (4, 1), size 4, and dtype int64:
[[0]
 [1]
 [2]
 [3]]


### a list as an index returns a 2d array, single index a 1d array

#### <div class="alert alert-info"> Exercise X (rows and columns)</div>

Write two functions, `get_rows` and `get_columns`, that get a two dimensional array as parameter.
They should return the list of rows and columns of the array, respectively. The rows and columns should be one dimensional arrays. You may use the *transpose* operation, which flips rows to columns, in your solution. The transpose is done by the `T` method:

In [33]:
a=np.random.randint(0, 10, (4,4))
print(a)
print(a.T)

[[0 1 9 9]
 [0 4 7 3]
 [2 7 2 0]
 [0 4 5 5]]
[[0 0 2 0]
 [1 4 7 4]
 [9 7 2 5]
 [9 3 0 5]]


Test your solution in the main function.
Example of usage:
```
a = np.array([[5, 0, 3, 3],
 [7, 9, 3, 5],
 [2, 4, 7, 6],
 [8, 8, 1, 6]])
get_rows(a)
[array([5, 0, 3, 3]), array([7, 9, 3, 5]), array([2, 4, 7, 6]), array([8, 8, 1, 6])]
get_columns(a)
[array([5, 7, 2, 8]), array([0, 9, 4, 8]), array([3, 3, 7, 1]), array([3, 5, 6, 6])]
```

## Array concatenation, splitting and stacking

The are two ways of combining several arrays into one bigger array: `concatenate` and `stack`. `Concatenate` takes n-dimensional arrays and returns an n-dimensional array, whereas `stack` takes n-dimensional arrays and returns n+1-dimensional array. Few examples of these:

In [34]:
a=np.arange(2)
b=np.arange(2,5)
print("a has shape %s: %s" % (a.shape, a))
print("b has shape %s: %s" % (b.shape, b))
np.concatenate((a,b))  # concatenating 1d arrays

a has shape (2,): [0 1]
b has shape (3,): [2 3 4]


array([0, 1, 2, 3, 4])

In [35]:
c=np.arange(1,5).reshape(2,2)
print("c has shape %s:" % (c.shape,), c, sep="\n")
np.concatenate((c,c))   # concatenating 2d arrays

c has shape (2, 2):
[[1 2]
 [3 4]]


array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

By default `concatenate` joins the arrays along axis 0. To join the arrays horizontally, add parameter `axis=1`:

In [36]:
np.concatenate((c,c), axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

If you want to catenate arrays with different dimensions, for example to add a new column to a 2d array, you must first  reshape the arrays to have same number of dimensions:

In [37]:
print("New row:")
print(np.concatenate((c,a.reshape(1,2))))
print("New column:")
print(np.concatenate((c,a.reshape(2,1)), axis=1))

New row:
[[1 2]
 [3 4]
 [0 1]]
New column:
[[1 2 0]
 [3 4 1]]


Using `stack` to create higher dimensional arrays from lower dimensional arrays:

In [38]:
np.stack((b,b))

array([[2, 3, 4],
       [2, 3, 4]])

In [39]:
np.stack((b,b), axis=1)

array([[2, 2],
       [3, 3],
       [4, 4]])

Inverse operation of `concatenate` is `split`. Its argument specifies either the number of equal parts the array is divided into, or it specifies explicitly the break points.

In [40]:
d=np.arange(12).reshape(6,2)
print("d:")
print(d)
d1,d2 = np.split(d, 2)
print("d1:")
print(d1)
print("d2:")
print(d2)

d:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
d1:
[[0 1]
 [2 3]
 [4 5]]
d2:
[[ 6  7]
 [ 8  9]
 [10 11]]


In [41]:
d=np.arange(12).reshape(2,6)
print("d:")
print(d)
parts=np.split(d, (2,3,5), axis=1)
for i, p in enumerate(parts):
    print("part %i:" % i)
    print(p)

d:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
part 0:
[[0 1]
 [6 7]]
part 1:
[[2]
 [8]]
part 2:
[[ 3  4]
 [ 9 10]]
part 3:
[[ 5]
 [11]]


#### <div class="alert alert-info"> Exercise X (row and column vectors)</div>

Create function `get_row_vectors` that returns a list of rows from the input array of shape `(n,m)`, but this time the rows must have shape `(1,n)`. Similarly, create function `get_columns_vectors` that returns the column of the input matrix having shape `(m,1)`.

#### <div class="alert alert-info"> Exercise X (diamond)</div>
Create a function `diamond` that returns a two dimensional integer array where the `1`s form a diamond shape. Rest of the numbers are `0`. The function should get a parameter that tells the length of a side of the diamond. Do this using the `eye` and `concatenate` functions of NumPy and array slicing.

Example of usage:
```
print(diamond(3))
[[0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]]
print(diamond(1))
[[1]]
```

## Fast computation using universal functions

In addition to providing a way to store and access multi-dimension arrays, NumPy also provides several routines to perform computations on them. One of the reasons for the popularity of NumPy is that these computations can be very efficient, much more efficient than what Python can normally do. The biggest bottle-necks in efficiency are the loops, which can be iterated millions, billions, or even more times. The loops should be as efficient as possible. What slows down loops in Python as the fact that Python is dynamically typed language. That means that at each expression Python has find out which are the typed of the arguments of the operations. Let's consider the following loop:

In [42]:
L=[1, 5.2, "ab"]
L2=[]
for x in L:
    L2.append(x*2)
print(L)

[1, 5.2, 'ab']


At each iteration of this loop Python has find out the type of the variable x, which can in this example be an int, a float or a string, and depending on this type call a different function to perform the "multiplication" by two. What makes NumPy efficient, is the requirement that each element in an array must be of the same type. This homogeneity of arrays makes it possible to create *vectorized* operation, which don't operate on single elements, but on arrays (or subarrays). The previous example using vectorized operations of NumPy is shown below.

In [43]:
a=np.array([2.1, 5.0, 17.2])
a2=a*2
print(a2)

[ 4.2 10.  34.4]


Because each iteration is using identical operations only the data differs, this can compiled into machine language, and then performed in one go, hence avoiding Python's dynamic typing. The name vector operation comes from linear algebra where the addition of two vectors \\(v=(v_1,v_2, \ldots, v_d)\\) and  \\(w=(w_1,w_2, \ldots, w_d)\\) is defined element-wise as \\(v+w = (v_1 + w_1,v_2 + w_2, \ldots, v_d + w_d)\\).

In addition to addition they are several mathematical functions defined in the vector form. The basic arithmetic operations are: addition `+`, subtraction `-`, negation `-`, multiplication `*`, division `/`, floor division `//`, exponentation `**`, and remainder `%`. 

The can be combined into more complicated expressions. An example:

In [44]:
b=np.array([-1, 3.2, 2.4])
print(-a**2 * b)

[   4.41   -80.    -710.016]


Several other mathematical functions are defined as well. A few examples of these can be found below.

In [45]:
print(np.abs(b))
print(np.cos(b))
print(np.exp(b))
print(np.log2(np.abs(b)))

[1.  3.2 2.4]
[ 0.54030231 -0.99829478 -0.73739372]
[ 0.36787944 24.5325302  11.02317638]
[0.         1.67807191 1.26303441]


In NumPy nomenclature these vector operations are called *ufuncs* (universal functions).

## Aggregations: max, min, sum, mean, standard deviation...

Aggregations allow us to condense the information in an array into just few numbers.

In [46]:
np.random.seed(0)
a=np.random.randint(-100, 100, (4,5))
print(a)
print("Minimum: %i, maximum: %i" %(a.min(), a.max()))
print("Sum: %i" % a.sum())
print("Mean: %f, standard deviation: %f" % (a.mean(), a.std()))

[[ 72 -53  17  92 -33]
 [ 95   3 -91 -79 -64]
 [-13 -30 -12  40 -42]
 [ 93 -61 -13  74 -12]]
Minimum: -91, maximum: 95
Sum: -17
Mean: -0.850000, standard deviation: 58.398866


Instead of aggregating over the whole array, we can aggregate over certain axes only as well:

In [47]:
b=np.random.randint(0, 10, (4,5))
print(b)
print("Column sums:", b.sum(axis=0))
print("Row sums:", b.sum(axis=1))

[[1 5 9 8 9]
 [4 3 0 3 5]
 [0 2 3 8 1]
 [3 3 3 7 0]]
Column sums: [ 8 13 15 26 15]
Row sums: [32 15 14 16]


NUOLIKUVAT SUUNNISTA TÄHÄN

<div class="alert alert-warning">
Note that most of the aggregation functions in NumPy have the corresponding method. In addition, Python language has builtin functions `sum`, `min`, `max`, `any`, and `all` for sequences. Make sure you don't accidentally use these for arrays, since they may have slightly different semantics, and they will be significantly slower than NumPy's functions and methods.
</div>

Python function | NumPy function | NumPy method
-------|----------------|-------------
sum    | np.sum         | a.sum
 -     | np.prod        | a.prod
 -     | np.mean        | a.mean
 -     | np.std         | a.std
 -     | np.var         | a.var
 min   | np.min         | a.min
 max   | np.max         | a.max
 -     | np.argmin      | a.argmin
 -     | np.argmax      | a.argmax
 -     | np.median      | -
 -     | np.percentile  | -
 any   | np.any         | a.any
 all   | np.all         | a.all
 
 

Let's measure how much slower Python's sum function is compared to Numpy's equivalent when aggrating over an array:

In [48]:
a=np.arange(1000)
%timeit np.sum(a)

2.67 µs ± 70 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [49]:
%timeit sum(a)

72.9 µs ± 5.06 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


The speed of NumPy is partly due to the fact that its arrays must have same type for all the elements. This requirement allows some efficient optimizations.

#### <div class="alert alert-info"> Exercise X (vector lengths)</div>

Write function `vector_lengths` that gets a two dimensional array of shape (n,m) as a parameter. Each row in this array corresponds to a vector. The function should return an array of shape (n,), that has the length of each vector in the input. The length is defined by the usual 
[Euclidean norm](<https://en.wikipedia.org/wiki/Norm_(mathematics&#41;#Euclidean_norm>). Don't use loops at all in your solution. Instead use vectorized operations. You must use at least the `np.sum` and the `np.sqrt` functions. You can't use the function `scipy.linalg.norm`. Test your function in the main function.

#### <div class="alert alert-info"> Exercise X (vector angles)</div>

Let x and y be m-dimensional vectors. The angle $\alpha$ between two vectors is defined by the equation
$\cos_{xy}(\alpha):=\frac{\langle x,y\rangle}{||x|| ||y||}$,
where the angle brackets denote the [inner product](https://en.wikipedia.org/wiki/Inner_product_space#Euclidean_space), and $||x||:=\sqrt{\langle x,x \rangle}$. 

Write function `vector_angles` that gets two arrays X and Y with same shape (n,m) as parameters. Each row in the arrays corresponds to a vector. The function should return vector of shape (n,) with the corresponding angles between vectors of `X` and `Y` in degrees, not in radians. Again, don't use loops, but use vectorized operations.

Note: function `np.arccos` is only defined on the domain [-1.0,1.0]. If you try to compute `np.arccos(1.000000001)`, it will fail. These kind of errors can occur due to use of finite precision in numerical computations. Force the argument to be in the correct range.

Test your solution in the main program.

## Broadcasting

We have seen that NumPy allows array operations that are performed element-wise. But NumPy also allows binary operations that don't require the two arrays to have the same shape. For example, we can add 3 to all elements of an array with the following expression:

In [50]:
np.arange(3) + np.array([4])

array([4, 5, 6])

In fact, because an array with only one element, say 3, can be thought of as a scalar 3, NumPy allows the following expression, which is equivalent to the above:

In [51]:
np.arange(3) + 4

array([4, 5, 6])

To get can idea of what operations are allowed, i.e. what shapes of the two arrays are compatible, it can be useful to think that before the binary operation is performed, NumPy tries to stretch the arrays to have the same shape. For example in above NumPy first stretched the array `np.array([4])` (or the scalar 4), to the array `np.array([4,4,4])` and then performed the element-wise addition. In NumPy this stretching is called *broadcasting*. TÄHÄN KUVA TILANTEESTA.

The argument arrays can of course have higher dimensions, as the next example shows:

In [52]:
a=np.full((3,3), 5)
b=np.arange(3)
print(a)
print(b)
print(a+b)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
[0 1 2]
[[5 6 7]
 [5 6 7]
 [5 6 7]]


In this example the second argument was first broadcasted to the array

In [53]:
np.array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

and then the addition was performed. And it may be that both of the argument arrays need to be broadcasted as in the next example:

In [54]:
a=np.arange(3)
b=np.arange(3).reshape((3,1))
info("a", a)
info("b", b)
info("a+b", a+b)

a has dim 1, shape (3,), size 3, and dtype int64:
[0 1 2]
b has dim 2, shape (3, 1), size 3, and dtype int64:
[[0]
 [1]
 [2]]
a+b has dim 2, shape (3, 3), size 9, and dtype int64:
[[0 1 2]
 [1 2 3]
 [2 3 4]]


To see what the arguments were broadcasted to before the binary operation, the function `np.broadcast_arrays` can be used:

In [55]:
broadcasted_a, broadcasted_b = np.broadcast_arrays(a,b)
info("broadcasted_a", broadcasted_a)
info("broadcasted_b", broadcasted_b)

broadcasted_a has dim 2, shape (3, 3), size 9, and dtype int64:
[[0 1 2]
 [0 1 2]
 [0 1 2]]
broadcasted_b has dim 2, shape (3, 3), size 9, and dtype int64:
[[0 0 0]
 [1 1 1]
 [2 2 2]]


So, both arrays were broadcasted, but in different ways. Let's next go through the [rules](https://docs.scipy.org/doc/numpy-1.14.0/reference/ufuncs.html#broadcasting) how the broadcasting work.


1. All input arrays with ndim smaller than the input array of largest ndim, have 1’s prepended to their shapes.
2. The size in each dimension of the output shape is the maximum of all the input sizes in that dimension.
3. An input can be used in the calculation if its size in a particular dimension either matches the output size in that dimension, or has value exactly 1.
4. If an input has a dimension size of 1 in its shape, the first data entry in that dimension will be used for all calculations along that dimension. In other words, the stepping machinery of the ufunc will simply not step along that dimension (the stride will be 0 for that dimension).



Finally an example of a situation where the two array are not compatible:

In [56]:
a=np.array([1,2,3])
b=np.array([4,5])
#a+b                 # This does not work since it violates the rule 3 above.

#### <div class="alert alert-info"> Exercise X (multiplication table revisited)</div>
Write function `multiplication_table` that gets a positive integer `n` as parameter. The function should return an array with shape (n,n). The element at index `(i,j)` should be `i*j`. Don't use `for` loops! In your solution, rely on broadcasting, the `np.arange` function, reshaping and vectorized operators. Example of usage:
````
print(multiplication_table(4))
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]
```

## Comparisons and masking

Just like NumPy allows element-wise arithmetic operations between arrays, for example addition of two arrays, it is possible to compare two arrays element-wise. For example

In [57]:
a=np.array([1,3,4])
b=np.array([2,2,7])
c = a < b
print(c)

[ True False  True]


Now we can query weather all comparisons resulted True, or whether some comparison resulted True:

In [58]:
print(c.all())   # were all True
print(c.any())   # was some comparison True

False
True


We can also count the number of comparisons that were True. This solution relies on the interpretation that True corresponds to 1 and False corresponds to 0:

In [59]:
print(np.sum(c))

2


Because the broadcasting rules apply also to comparison, we can write

In [60]:
print(a > 0)

[ True  True  True]


To try these operations on real data, we download some weather statistics from Helsinki (Kumpula) weather statition. More precisely we will get the daily average temperatures from year 2017. We use the pandas library, which we will cover later during this course, to load the data.

In [61]:
import pandas as pd
a=pd.read_csv("https://www.cs.helsinki.fi/u/jttoivon/dap/data/fmi/kumpula-weather-2017.csv")['Air temperature (degC)'].values

In [62]:
a

array([  0.6,  -3.9,  -6.5, -12.8, -17.8, -17.8,  -3.8,  -0.5,   0.5,
         1.7,  -1.6,  -2.8,   1.1,   0.8,  -2.8,  -4.2,  -3.5,   1.1,
         1.6,  -0.6,  -1.8,   1. ,   0.1,  -2.2,  -3.8,   1.9,   1.6,
         0.8,   0.6,   1. ,   0.2,  -0.6,  -0.8,  -0.2,   0.4,  -2.5,
        -7.3, -12.1,  -8.8, -10.1,  -8.3,  -5.4,  -2.7,   1.5,   4.4,
         0. ,   0.5,   1.5,   1.9,   2.2,   0.4,  -2.5,  -4.6,  -0.7,
        -5.3,  -5.6,  -2. ,  -2.3,   2.1,   1.5,   1.5,   0.9,  -1.8,
        -4.2,  -4.2,  -2.9,   0.2,   1.2,   1.4,   2.2,  -0.9,   0.6,
         0.6,   3.8,   3.4,   2. ,   1.6,   0.6,   0.2,   1.6,   2.3,
         2.5,   0.5,   1.9,   4.8,   6.6,   2.4,   0.4,  -0.4,   0.2,
         1.5,   4.3,   3. ,   3.8,   3.3,   4.7,   4.1,   3.3,   3.7,
         6. ,   4.3,   1.8,   1.2,  -0.5,  -1.4,  -1.7,   0.6,   0.3,
         1.2,   2.5,   5.7,   3.1,   2.9,   3.6,   2.8,   3.2,   4.4,
         4.1,   2.3,   2.2,   7.6,   9.4,   9.2,   6.7,  10.1,  11.1,
         6.1,   4.4,

In [63]:
print("Number of days with the temperature below zero", np.sum(a < 0))

Number of days with the temperature below zero 49


In core Python we can combine truth values using the `and`, `or`, and `not` keywords. For boolean array however we have to use operators `&`, `|`, and `~`, respectively. An example of these:

In [64]:
np.sum((0 < a) & (a < 10))     # Temperature is greater than 0 and smaller that 10 

185

Note that we had to use parentheses around the comparisons, because the precedence of the `&` is higher than of `<`, and so it would have been performed before the comparisons.

Another use of boolean arrays is that they can be used to select a subset of elements. For example

In [65]:
c = a > 0
print(c[:10])    # print only the first ten elements
print(a[c])      # Select only the positive temperatures 

[ True False False False False False False False  True  True]
[ 0.6  0.5  1.7  1.1  0.8  1.1  1.6  1.   0.1  1.9  1.6  0.8  0.6  1.
  0.2  0.4  1.5  4.4  0.5  1.5  1.9  2.2  0.4  2.1  1.5  1.5  0.9  0.2
  1.2  1.4  2.2  0.6  0.6  3.8  3.4  2.   1.6  0.6  0.2  1.6  2.3  2.5
  0.5  1.9  4.8  6.6  2.4  0.4  0.2  1.5  4.3  3.   3.8  3.3  4.7  4.1
  3.3  3.7  6.   4.3  1.8  1.2  0.6  0.3  1.2  2.5  5.7  3.1  2.9  3.6
  2.8  3.2  4.4  4.1  2.3  2.2  7.6  9.4  9.2  6.7 10.1 11.1  6.1  4.4
  1.5  1.5  2.9  5.1  7.5  9.8  9.   7.3  9.4 11.2 16.1 16.9 14.7 14.6
 13.3 12.4 14.1 14.1  9.6 13.2 14.1  9.6 10.8  6.5  6.2 10.   9.9 10.4
 14.5 16.4 12.3 14.  16.3 16.8 12.6 12.6 14.8 15.1 18.4 19.3 16.9 17.8
 12.7 12.4 12.2 10.8 12.9 14.  13.5 13.7 15.3 16.3 17.2 14.1 16.4 14.5
 14.1 14.  11.5 14.7 16.1 17.4 18.  16.8 16.8 14.7 15.3 16.7 18.  15.4
 15.  13.7 14.6 15.8 15.6 16.9 15.7 16.1 17.2 19.  19.1 17.8 18.3 17.8
 18.9 17.5 18.2 16.6 17.1 16.  15.2 17.2 18.3 18.7 18.1 19.6 17.4 16.1
 16.4 17.6 19.  

This operation is called *masking*. It can also be used to assign a new value. For example the following zeroes out the  negative temperatures:

In [66]:
a[~c] = 0
print(a)

[ 0.6  0.   0.   0.   0.   0.   0.   0.   0.5  1.7  0.   0.   1.1  0.8
  0.   0.   0.   1.1  1.6  0.   0.   1.   0.1  0.   0.   1.9  1.6  0.8
  0.6  1.   0.2  0.   0.   0.   0.4  0.   0.   0.   0.   0.   0.   0.
  0.   1.5  4.4  0.   0.5  1.5  1.9  2.2  0.4  0.   0.   0.   0.   0.
  0.   0.   2.1  1.5  1.5  0.9  0.   0.   0.   0.   0.2  1.2  1.4  2.2
  0.   0.6  0.6  3.8  3.4  2.   1.6  0.6  0.2  1.6  2.3  2.5  0.5  1.9
  4.8  6.6  2.4  0.4  0.   0.2  1.5  4.3  3.   3.8  3.3  4.7  4.1  3.3
  3.7  6.   4.3  1.8  1.2  0.   0.   0.   0.6  0.3  1.2  2.5  5.7  3.1
  2.9  3.6  2.8  3.2  4.4  4.1  2.3  2.2  7.6  9.4  9.2  6.7 10.1 11.1
  6.1  4.4  1.5  1.5  2.9  5.1  7.5  9.8  9.   7.3  9.4 11.2 16.1 16.9
 14.7 14.6 13.3 12.4 14.1 14.1  9.6 13.2 14.1  9.6 10.8  6.5  6.2 10.
  9.9 10.4 14.5 16.4 12.3 14.  16.3 16.8 12.6 12.6 14.8 15.1 18.4 19.3
 16.9 17.8 12.7 12.4 12.2 10.8 12.9 14.  13.5 13.7 15.3 16.3 17.2 14.1
 16.4 14.5 14.1 14.  11.5 14.7 16.1 17.4 18.  16.8 16.8 14.7 15.3 16.7
 18.  15.

Compare this result with the original array `a` to make sure you understand what's going on!

#### <div class="alert alert-info"> Exercise X (column comparison)</div>

Write function `column_comparison` that gets a two dimensional array as parameter. The function should return a new array containing those rows from the input that have the value in the second column larger than in the second last column. You may assume that the input contains at least two columns. Don't use loops, but instead vectorized operations. Try out your function in the main function. Example input and output:

#### <div class="alert alert-info"> Exercise X (first half second half)</div>

Write function `first_half_second_half` that gets a two dimensional array of shape `(n,2*m)` as a parameter. The input array has `2*m` columns. The output from the function should be a matrix with those rows from the input that have the sum of the first `m` elements larger than the sum of the last `m` elements on the row. Your solution should call the `np.sum` function or the corresponding method exactly twice.

## Fancy indexing

Using indexing we can get a single elements from an array. If we wanted multiple (not necessarily contiguous) elements, we would have to index several times:

In [67]:
np.random.seed(0)
a=np.random.randint(0, 20,20)
a2=np.array([a[2], a[5], a[7]])
print(a)
print(a2)

[12 15  0  3  3  7  9 19 18  4  6 12  1  6  7 14 17  5 13  8]
[ 0  7 19]


That's quite verbose. *Fancy indexing* provides a concise syntax for accessing multiple elements:

In [68]:
idx=[2,5,7]           # List of indices
print(a[idx])         # In fancy indexing in place of a single index, we can provide a list of indices
print(a[[2,5,7]])     # Or directly

[ 0  7 19]
[ 0  7 19]


We can also assign to multiple elements through fancy indexing:

In [69]:
a[idx] = -1
print(a)

[12 15 -1  3  3 -1  9 -1 18  4  6 12  1  6  7 14 17  5 13  8]


Fancy indexing works also for higher dimensional arrays:

In [70]:
b=np.random.randint(0,10, (4,4))
print(b)
row=np.array([0,2])
col=np.array([1,3])
print(b[row, col])

[[9 4 3 0]
 [3 5 0 2]
 [3 8 1 3]
 [3 3 7 0]]
[4 3]


Note that the result array was one dimensional! The shape of the result array is defined by the shape of the index arrays, not by the shape of the original array. The next example will demonstrate this.

In [71]:
row2=np.array([[0, 0], [2,2]])
col2=np.array([[1,3], [1,3]])
print(row2)
print(col2)
print(b[row2, col2])

[[0 0]
 [2 2]]
[[1 3]
 [1 3]]
[[4 0]
 [8 3]]


Both index arrays, row and col, had shape (2,2), so also the result was of shape (2,2). However, this form has some repetition in the indices. But we can rely that the broadcasting rules will enable us to avoid the repetition:

In [72]:
row2=row.reshape(2,1)   # has shape (2, 1)
col2=col.reshape(1,2)   # has shape (1, 2)
print(row2)
print(col2)
print(b[row2, col2])    # the index arrays will be broadcasted here to shape (2,2)

[[0]
 [2]]
[[1 3]]
[[4 0]
 [8 3]]


One can also combine normal indexing, slicing and fancy indexing:

In [73]:
b[:,[0,2]]

array([[9, 3],
       [3, 0],
       [3, 1],
       [3, 7]])

## Sorting arrays



In [74]:
a=np.array([2,1,4,3,5])
print(np.sort(a))          # Does not modify the argument
print(a)

[1 2 3 4 5]
[2 1 4 3 5]


In [75]:
a.sort()            # Modifies the argument
print(a)

[1 2 3 4 5]


In [76]:
b=np.random.randint(0,10, (4,4))
print(b)

[[1 9 9 0]
 [4 7 3 2]
 [7 2 0 0]
 [4 5 5 6]]


In [77]:
np.sort(b, axis=0)           # sort each column

array([[1, 2, 0, 0],
       [4, 5, 3, 0],
       [4, 7, 5, 2],
       [7, 9, 9, 6]])

In [78]:
np.sort(b, axis=1)           # Sort each row

array([[0, 1, 9, 9],
       [2, 3, 4, 7],
       [0, 0, 2, 7],
       [4, 5, 5, 6]])

A related operation is the argsort function. Which doesn't sort the elements, but returns the indices of the sorted elements. An example will demonstrate this:

In [79]:
a=np.array([2,1,4,3,5])
print("Array a:", a)
idx = np.argsort(a)
print("Indices:", idx)

Array a: [2 1 4 3 5]
Indices: [1 0 3 2 4]


These indices say that the smallest element of the array is in position 1 of `a`, second smallest elements is in position 0 of `a`, third smallest is in position 3, and so on. We can verify that these indices will indeed order the elements using fancy indexing:

In [80]:
print(a[idx])

[1 2 3 4 5]


#### <div class="alert alert-info"> Exercise X (most frequent first)</div>

Write function `most_frequent_first` that gets a two dimensional array and an index `c` of a column as parameters. The function should then return the array whose rows are sorted so that those rows with the most frequent element in column `c` come first, then come the rows with the second most frequent element in column `c`, and so on.

Example of usage:
```
a:
 [[5 0 3 3 7 9 3 5 2 4]
 [7 6 8 8 1 6 7 7 8 1]
 [5 9 8 9 4 3 0 3 5 0]
 [2 3 8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7 2 0]
 [0 4 5 5 6 8 4 1 4 9]
 [8 1 1 7 9 9 3 6 7 2]
 [0 3 5 9 4 4 6 4 4 3]
 [4 4 8 4 3 7 5 5 0 1]
 [5 9 3 0 5 0 1 2 4 2]]
print(most_frequent_first(a, -1))
 [[4 4 8 4 3 7 5 5 0 1]
 [2 3 8 1 3 3 3 7 0 1]
 [7 6 8 8 1 6 7 7 8 1]
 [5 9 3 0 5 0 1 2 4 2]
 [8 1 1 7 9 9 3 6 7 2]
 [9 9 0 4 7 3 2 7 2 0]
 [5 9 8 9 4 3 0 3 5 0]
 [0 3 5 9 4 4 6 4 4 3]
 [0 4 5 5 6 8 4 1 4 9]
 [5 0 3 3 7 9 3 5 2 4]]
```

If we look at the last column, we see that the number 1 appears three times, then both numbers 2 and 0 appear twice, and lastly numbers 3, 9, and 4 appear only once. Note that, for example, among those rows that contain in column `c` a number that appear twice the order can be arbitrary.

Hint: the function `np.unique` may be useful.

## Matrix operations

The `*` operator is NumPy corresponds to the element-wise product of two arrays. However, very often we would like to use the *matrix multiplication*. As a reminder, if $a$ and $b$ are two matrices with shapes $n \times k$ and $k \times m$ respectively, then the matrix product of $a$ and $b$ is the matrix $c$ with shape $n \times m$, where $c_{ij} = \sum_{h=1}^k a_{ih} b_{hj}$ for $1 \le i \le n$ and $1 \le j \le m$. In NumPy we can compute the matrix product using the `np.matmul` function or the `@` operator. An example of this:

In [81]:
np.random.seed(0)
a=np.random.randint(0,10, (3,2))
b=np.random.randint(0,10, (2,4))
print(a)
print(b)

[[5 0]
 [3 3]
 [7 9]]
[[3 5 2 4]
 [7 6 8 8]]


In [82]:
c=np.matmul(a,b)
info("c", c)

c has dim 2, shape (3, 4), size 12, and dtype int64:
[[ 15  25  10  20]
 [ 30  33  30  36]
 [ 84  89  86 100]]


In [83]:
print(a@b)      # This can be more convenient when complex expressions are used

[[ 15  25  10  20]
 [ 30  33  30  36]
 [ 84  89  86 100]]


So, matrices are just two dimensional arrays with the product defined differently from the element-wise product. Note that for the matrix product to be defined, the two matrices have to have compatible shapes. So the following would produce an error:

In [84]:
# a@a   # Try uncommenting to see the error message

Let's test some basic identities that should hold for an [invertible matrix](https://en.wikipedia.org/wiki/Invertible_matrix):

In [85]:
s=np.array([[1, 6, 7],
 [7, 8, 1],
 [5, 9, 8]])
print(s)
s_inv = np.linalg.inv(s)
print(s_inv)
print(s @ s_inv)                            # This should be pretty close to the identity matrix np.eye(3)
print(s_inv @ s)                            # Same here

[[1 6 7]
 [7 8 1]
 [5 9 8]]
[[-0.61111111 -0.16666667  0.55555556]
 [ 0.56666667  0.3        -0.53333333]
 [-0.25555556 -0.23333333  0.37777778]]
[[ 1.00000000e+00 -8.32667268e-17  4.44089210e-16]
 [-5.55111512e-17  1.00000000e+00  4.44089210e-16]
 [-4.44089210e-16  0.00000000e+00  1.00000000e+00]]
[[ 1.00000000e+00  9.99200722e-16 -8.88178420e-16]
 [ 0.00000000e+00  1.00000000e+00  8.88178420e-16]
 [ 2.22044605e-16 -4.44089210e-16  1.00000000e+00]]


In [86]:
x=np.array([1,4,2])
y = s @ x                  # Transforms x to y
print(y)
print(s_inv @ y)           # Transforms y back to x

[39 41 57]
[1. 4. 2.]


#### <div class="alert alert-info"> Exercise X (matrix power)</div>

Repeat the functionality of the Numpy function `numpy.linalg.matrix_power`, which raises a square matrix of shape (m,m) to the `n`th power. Here the multiplication is the matrix multiplication. Square matrix `a` raised to power `n` is therefore `a @ a @ ... @ a` where `a` is repeated `n` times. When n is zero then $a^0$ is equal to `np.eye(m)`.

Part 1.

Write function `matrix_power` that gets as first argument a square matrix `a` and as second argument a non-negative integer `n`. The function should return the matrix `a` multiplied by itself `n-1` times.
Use Python's reduce function and a generator expression.

Part 2.

Extend the `matrix_power` function.
For negative powers, we define $a^{-1}$ to be equal to the multiplicative inverse of `a`. You can use NumPy's function `numpy.linalg.inv` for this. And you may assume that the input matrix is invertible.

#### <div class="alert alert-info"> Exercise X (correlation)</div>

Load the iris dataset using the provided function `load()` in the stub solution. The four columns of the returned array correspond to
* sepal length (cm)
* sepal width (cm)
* petal length (cm)
* petal width (cm)

Part 1. What is the Pearson correlation between the variables `sepal length` and `petal length`. Compute this using the `scipy.stats.pearsonr` function. It returns a tuple whose first element is the correlation. Write a function `lengths` that loads the data and return the correlation.

Part 2. What are the correlations between all the variables. Write a function `correlations` that returns an array of shape (4,4) containing the correlations. Use the function `np.corrcoef`. Which pair of variables is the most highly correlated?

Note the input formats of both functions `pearsonr` and `corrcoef`.

## Solving system of linear equations

The Scipy library has function [`np.linalg.solve`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve.html) to solve systems of linear equations. The `solve` function gets as parameters the coefficient matrix and the vector containing the constant term. Below is an example of the general system of linear equations

\\(a_{11}x_1 + a_{12}x_2 + \cdots a_{1m}x_m = b_1\\
a_{21}x_1 + a_{22}x_2 + \cdots a_{2m}x_m = b_2\\
\cdots\\
a_{n1}x_1 + a_{n2}x_2 + \cdots a_{nm}x_m = b_n\\
\\)


and the equivalent matrix form
\\(A \cdot x = b\\)
where $A$ has shape `(n,m)`, the unknown $x$ has shape `(m,1)`, and $b$ has shape `(n,1)`.

#### <div class="alert alert-info"> Exercise X (meeting lines)</div>

Write function `meeting_lines` that gets the coefficients of two lines as parameters and returns the point where the two lines meet. The equations for the lines are $y=a_1x + b_1$ and $y=a_2x + b_2$. Use the `np.linalg.solve` function. Create a main function to test your solution.

#### <div class="alert alert-info"> Exercise X (meeting planes)</div>
Write function `meeting_planes` that gets the coefficients of three planes as parameters and returns the point where the planes meet. The equations for the planes are:
$z =a_1y + b_1x+ c_1$,
$z =a_2y + b_2x+ c_2$, and
$z =a_3y + b_3x+ c_3$.


#### <div class="alert alert-info"> Exercise X (almost meeting lines)</div>
In the earlier "meeting lines" exercise there is a problem if the lines don't meet at all. Extend that solution so that it tells the meeting point if it exists, and otherwise finds the point that is closest to the both lines.
You can use the `numpy.linalg.lstsq` for this.

Example of usage:
```
(y, x), exact = almost_meeting_lines(1, 2, -1, 0)
print(y, x, exact)
1.000000 -1.000000 True
```